ros2_process_manager:
  refresh_interval_ms: 6000
  ros2_process_identifiers:
    - "--ros-args"
    - "__node:="
  ros2_process_comm:
    - "ros2"
    - "python3"
  max_process_name_length: 80

  # specified processes to be monitored (use keyword of commandline)
  monitored_processes:
    - "keyword": "ac_driver/ms_node"
      "name": "ms_node"
    - "keyword": "postprocess/lib/postprocess/postprocess_node"
      "name": "postprocess_node"
    - "keyword": "perception/lib/perception/yolov8_node"
      "name": "yolov8_node"

resource_monitor:
  enable: true
  exec_interval_ms: 1000
  publish_topic_name: "/diagnostics"

frequency_monitor:
  enable: true
  exec_interval_ms: 1000
  publish_topic_name: "/diagnostics"

  topics:
  - name: "/diagnostics"
    min_freq: 0.5
  - name: "/parameter_events"
    min_freq: 0.0
  - name: "/rosout"
    min_freq: 0.0

timestamp_monitor:
  enable: true
  exec_interval_ms: 2000
  publish_topic_name: "/diagnostics"

  topics:
    - name: "/diagnostics"
      max_difference_ms: 1000
